name: "pnpm install"

runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install pnpm
      uses: pnpm/action-setup@v2

    - name: Use Node 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: "pnpm"

    - name: Install dependencies
      run: pnpm install --config.platform=linux --config.architecture=x64
      shell: bash
