name: Install playwright binaries

runs:
  using: "composite"
  steps:
    - name: Cache playwright binaries
      id: playwright-cache
      uses: actions/cache@v3
      with:
        path: |
          ~/Library/Caches/ms-playwright
          ~/.cache/ms-playwright
          ${{ github.workspace }}/node_modules/playwright
        key: cache-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: cache-playwright-

    - name: Install dependencies
      run: pnpm install --config.platform=linux --config.architecture=x64
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      shell: bash

    - name: pnpm playwright install
      shell: bash
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: pnpm exec playwright install --with-deps
