name: Call Cache Build & E2E
on:
  push:
    branches:
      - shubham/for-1607-use-cache-in-e2e-docker-build

# on:
#   workflow_call:

jobs:
  build:
    name: Call cache build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/cache-build-web

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Start PostgreSQL
        run: |
          DATABASE_URL=postgresql://postgres:postgres@localhost:5432/formbricks?schema=public && cd packages/database && pnpm db:up &
          for attempt in {1..20}; do
            if nc -zv localhost 5432; then
              echo "Ready"
              break
            fi
            echo "Waiting..."
            sleep 5
          done
          pnpm db:migrate:dev
      - name: Serve packages for lazy loading
        run: |
          cd packages/surveys && pnpm serve &
      - name: Run App
        run: |
          NODE_ENV=test pnpm start --filter=web &
          for attempt in {1..20}; do
            if [ $(curl -o /dev/null -s -w "%{http_code}" http://localhost:3000/health) -eq 200 ]; then
              echo "Ready"
              break
            fi
            echo "Waiting..."
            sleep 10
          done
      - name: Test Serve endpoints
        run: |
          curl -s http://localhost:3003
      - name: Run E2E Tests
        run: |
          pnpm test:e2e
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
