name: Cache production build binaries
on:
  push:
    branches:
      - shubham/for-1607-use-cache-in-e2e-docker-build

jobs:
  build:
    name: Cache Formbricks-web
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Cache production build
        uses: actions/cache@v3
        id: cache-build
        # Add node version in cache key later
        env:
          cache-name: prod-build
          key-1: ${{ hashFiles('yarn.lock') }}
          key-2: ${{ hashFiles('apps/**/**.[jt]s', 'apps/**/**.[jt]sx', 'packages/**/**.[jt]s', 'packages/**/**.[jt]sx', '!**/node_modules') }}
          key-3: ${{ github.event.pull_request.number || github.ref }}
        with:
          path: |
            ${{ github.workspace }}/apps/web/.next
            **/.turbo/**
            **/dist/**
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.key-1 }}-${{ env.key-2 }}-${{ env.key-3 }}
      - run: |
          pnpm install --config.platform=linux --config.architecture=x64
          cp .env.example .env
          SECRET=$(openssl rand -hex 32)
          echo "ENCRYPTION_KEY=$SECRET" >> $GITHUB_ENV
          pnpm build --filter=web...

        if: steps.cache-build.outputs.cache-hit != 'true'
        shell: bash
