name: KAMAL Deploy

on:
  push:
    branches:
      - shubham/kamal-test

jobs:
  Deploy:
    if: ${{ github.event_name == 'push'}}
    runs-on: ubuntu-latest

    env:
      DOCKER_BUILDKIT: 1
      WEBAPP_URL: ${{ secrets.WEBAPP_URL }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      SHORT_URL_BASE: ${{ secrets.SHORT_URL_BASE }}
      MAIL_FROM: ${{ secrets.MAIL_FROM }}
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_SECURE_ENABLED: ${{ secrets.SMTP_SECURE_ENABLED }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      EMAIL_VERIFICATION_DISABLED: ${{ secrets.EMAIL_VERIFICATION_DISABLED }}
      PASSWORD_RESET_DISABLED: ${{ secrets.PASSWORD_RESET_DISABLED }}
      SIGNUP_DISABLED: ${{ secrets.SIGNUP_DISABLED }}
      EMAIL_AUTH_DISABLED: ${{ secrets.EMAIL_AUTH_DISABLED }}
      INVITE_DISABLED: ${{ secrets.INVITE_DISABLED }}
      PRIVACY_URL: ${{ secrets.PRIVACY_URL }}
      TERMS_URL: ${{ secrets.TERMS_URL }}
      IMPRINT_URL: ${{ secrets.IMPRINT_URL }}
      GITHUB_ID: ${{ secrets.GITHUB_ID }}
      GITHUB_SECRET: ${{ secrets.GITHUB_SECRET }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      AZUREAD_CLIENT_ID: ${{ secrets.AZUREAD_CLIENT_ID }}
      AZUREAD_CLIENT_SECRET: ${{ secrets.AZUREAD_CLIENT_SECRET }}
      AZUREAD_TENANT_ID: ${{ secrets.AZUREAD_TENANT_ID }}
      OIDC_CLIENT_ID: ${{ secrets.OIDC_CLIENT_ID }}
      OIDC_CLIENT_SECRET: ${{ secrets.OIDC_CLIENT_SECRET }}
      OIDC_ISSUER: ${{ secrets.OIDC_ISSUER }}
      OIDC_DISPLAY_NAME: ${{ secrets.OIDC_DISPLAY_NAME }}
      OIDC_SIGNING_ALGORITHM: ${{ secrets.OIDC_SIGNING_ALGORITHM }}
      CRON_SECRET: ${{ secrets.CRON_SECRET }}
      ASSET_PREFIX_URL: ${{ secrets.ASSET_PREFIX_URL }}
      NOTION_OAUTH_CLIENT_ID: ${{ secrets.NOTION_OAUTH_CLIENT_ID }}
      NOTION_OAUTH_CLIENT_SECRET: ${{ secrets.NOTION_OAUTH_CLIENT_SECRET }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
      GOOGLE_SHEETS_CLIENT_ID: ${{ secrets.GOOGLE_SHEETS_CLIENT_ID }}
      GOOGLE_SHEETS_CLIENT_SECRET: ${{ secrets.GOOGLE_SHEETS_CLIENT_SECRET }}
      GOOGLE_SHEETS_REDIRECT_URL: ${{ secrets.GOOGLE_SHEETS_REDIRECT_URL }}
      AIRTABLE_CLIENT_ID: ${{ secrets.AIRTABLE_CLIENT_ID }}
      ENTERPRISE_LICENSE_KEY: ${{ secrets.ENTERPRISE_LICENSE_KEY }}
      DEFAULT_TEAM_ID: ${{ secrets.DEFAULT_TEAM_ID }}
      DEFAULT_TEAM_ROLE: ${{ secrets.DEFAULT_TEAM_ROLE }}
      ONBOARDING_DISABLED: ${{ secrets.ONBOARDING_DISABLED }}
      CUSTOMER_IO_API_KEY: ${{ secrets.CUSTOMER_IO_API_KEY }}
      CUSTOMER_IO_SITE_ID: ${{ secrets.CUSTOMER_IO_SITE_ID }}
      RATE_LIMITING_DISABLED: ${{ secrets.RATE_LIMITING_DISABLED }}
      NEXT_PUBLIC_POSTHOG_API_KEY: ${{ secrets.NEXT_PUBLIC_POSTHOG_API_KEY }}
      NEXT_PUBLIC_POSTHOG_API_HOST: ${{ secrets.NEXT_PUBLIC_POSTHOG_API_HOST }}
      NEXT_PUBLIC_FORMBRICKS_API_HOST: ${{ secrets.NEXT_PUBLIC_FORMBRICKS_API_HOST }}
      NEXT_PUBLIC_FORMBRICKS_ENVIRONMENT_ID: ${{ secrets.NEXT_PUBLIC_FORMBRICKS_ENVIRONMENT_ID }}
      NEXT_PUBLIC_FORMBRICKS_ONBOARDING_SURVEY_ID: ${{ secrets.NEXT_PUBLIC_FORMBRICKS_ONBOARDING_SURVEY_ID }}
      NODE_ENV: production
      KAMAL_REGISTRY_USERNAME: ${{ secrets.KAMAL_REGISTRY_USERNAME }}
      KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
      KAMAL_CONTAINER_IMAGE: ${{ secrets.KAMAL_CONTAINER_IMAGE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install kamal

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Manual DOcker Login
        run: docker login -u ${{ secrets.KAMAL_REGISTRY_USERNAME }} -p ${{ secrets.KAMAL_REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Create .env file
        run: |
          echo "WEBAPP_URL=$WEBAPP_URL" >> .env
          echo "DATABASE_URL=$DATABASE_URL" >> .env
          echo "NEXTAUTH_SECRET=$NEXTAUTH_SECRET" >> .env
          echo "ENCRYPTION_KEY=$ENCRYPTION_KEY" >> .env
          echo "SHORT_URL_BASE=$SHORT_URL_BASE" >> .env
          echo "MAIL_FROM=$MAIL_FROM" >> .env
          echo "SMTP_HOST=$SMTP_HOST" >> .env
          echo "SMTP_PORT=$SMTP_PORT" >> .env
          echo "SMTP_SECURE_ENABLED=$SMTP_SECURE_ENABLED" >> .env
          echo "SMTP_USER=$SMTP_USER" >> .env
          echo "SMTP_PASSWORD=$SMTP_PASSWORD" >> .env
          echo "EMAIL_VERIFICATION_DISABLED=$EMAIL_VERIFICATION_DISABLED" >> .env
          echo "PASSWORD_RESET_DISABLED=$PASSWORD_RESET_DISABLED" >> .env
          echo "SIGNUP_DISABLED=$SIGNUP_DISABLED" >> .env
          echo "EMAIL_AUTH_DISABLED=$EMAIL_AUTH_DISABLED" >> .env
          echo "INVITE_DISABLED=$INVITE_DISABLED" >> .env
          echo "PRIVACY_URL=$PRIVACY_URL" >> .env
          echo "TERMS_URL=$TERMS_URL" >> .env
          echo "IMPRINT_URL=$IMPRINT_URL" >> .env
          echo "GITHUB_ID=$GITHUB_ID" >> .env
          echo "GITHUB_SECRET=$GITHUB_SECRET" >> .env
          echo "GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID" >> .env
          echo "GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET" >> .env
          echo "AZUREAD_CLIENT_ID=$AZUREAD_CLIENT_ID" >> .env
          echo "AZUREAD_CLIENT_SECRET=$AZUREAD_CLIENT_SECRET" >> .env
          echo "AZUREAD_TENANT_ID=$AZUREAD_TENANT_ID" >> .env
          echo "OIDC_CLIENT_ID=$OIDC_CLIENT_ID" >> .env
          echo "OIDC_CLIENT_SECRET=$OIDC_CLIENT_SECRET" >> .env
          echo "OIDC_ISSUER=$OIDC_ISSUER" >> .env
          echo "OIDC_DISPLAY_NAME=$OIDC_DISPLAY_NAME" >> .env
          echo "OIDC_SIGNING_ALGORITHM=$OIDC_SIGNING_ALGORITHM" >> .env
          echo "CRON_SECRET=$CRON_SECRET" >> .env
          echo "ASSET_PREFIX_URL=$ASSET_PREFIX_URL" >> .env
          echo "NOTION_OAUTH_CLIENT_ID=$NOTION_OAUTH_CLIENT_ID" >> .env
          echo "NOTION_OAUTH_CLIENT_SECRET=$NOTION_OAUTH_CLIENT_SECRET" >> .env
          echo "STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY" >> .env
          echo "STRIPE_WEBHOOK_SECRET=$STRIPE_WEBHOOK_SECRET" >> .env
          echo "GOOGLE_SHEETS_CLIENT_ID=$GOOGLE_SHEETS_CLIENT_ID" >> .env
          echo "GOOGLE_SHEETS_CLIENT_SECRET=$GOOGLE_SHEETS_CLIENT_SECRET" >> .env
          echo "GOOGLE_SHEETS_REDIRECT_URL=$GOOGLE_SHEETS_REDIRECT_URL" >> .env
          echo "AIRTABLE_CLIENT_ID=$AIRTABLE_CLIENT_ID" >> .env
          echo "ENTERPRISE_LICENSE_KEY=$ENTERPRISE_LICENSE_KEY" >> .env
          echo "DEFAULT_TEAM_ID=$DEFAULT_TEAM_ID" >> .env
          echo "DEFAULT_TEAM_ROLE=$DEFAULT_TEAM_ROLE" >> .env
          echo "ONBOARDING_DISABLED=$ONBOARDING_DISABLED" >> .env
          echo "CUSTOMER_IO_API_KEY=$CUSTOMER_IO_API_KEY" >> .env
          echo "CUSTOMER_IO_SITE_ID=$CUSTOMER_IO_SITE_ID" >> .env
          echo "RATE_LIMITING_DISABLED=$RATE_LIMITING_DISABLED" >> .env
          echo "NEXT_PUBLIC_POSTHOG_API_KEY=$NEXT_PUBLIC_POSTHOG_API_KEY" >> .env
          echo "NEXT_PUBLIC_POSTHOG_API_HOST=$NEXT_PUBLIC_POSTHOG_API_HOST" >> .env
          echo "NEXT_PUBLIC_FORMBRICKS_API_HOST=$NEXT_PUBLIC_FORMBRICKS_API_HOST" >> .env
          echo "NEXT_PUBLIC_FORMBRICKS_ENVIRONMENT_ID=$NEXT_PUBLIC_FORMBRICKS_ENVIRONMENT_ID" >> .env
          echo "NEXT_PUBLIC_FORMBRICKS_ONBOARDING_SURVEY_ID=$NEXT_PUBLIC_FORMBRICKS_ONBOARDING_SURVEY_ID" >> .env
          echo "NODE_ENV=production" >> .env
          echo "KAMAL_REGISTRY_USERNAME=$KAMAL_REGISTRY_USERNAME" >> .env
          echo "KAMAL_REGISTRY_PASSWORD=$KAMAL_REGISTRY_PASSWORD" >> .env
          echo "KAMAL_CONTAINER_IMAGE=$KAMAL_CONTAINER_IMAGE" >> .env
    
      - name: Run deploy command
        run: kamal setup
