name: Kamal Deploy
concurrency:
  group: deploy-to-kamal
  cancel-in-progress: false

on:
  push:
    branches:
      - shubham/kamal-test

jobs:
  Deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      WEBAPP_URL: ${{ secrets.KAMAL_WEBAPP_URL }}
      DATABASE_URL: ${{ secrets.KAMAL_DATABASE_URL }}
      NEXTAUTH_SECRET: ${{ secrets.KAMAL_NEXTAUTH_SECRET }}
      ENCRYPTION_KEY: ${{ secrets.KAMAL_ENCRYPTION_KEY }}
      SHORT_URL_BASE: ${{ secrets.KAMAL_SHORT_URL_BASE }}
      MAIL_FROM: ${{ secrets.KAMAL_MAIL_FROM }}
      SMTP_HOST: ${{ secrets.KAMAL_SMTP_HOST }}
      SMTP_PORT: ${{ secrets.KAMAL_SMTP_PORT }}
      SMTP_SECURE_ENABLED: ${{ secrets.KAMAL_SMTP_SECURE_ENABLED }}
      SMTP_USER: ${{ secrets.KAMAL_SMTP_USER }}
      SMTP_PASSWORD: ${{ secrets.KAMAL_SMTP_PASSWORD }}
      EMAIL_VERIFICATION_DISABLED: ${{ secrets.KAMAL_EMAIL_VERIFICATION_DISABLED }}
      PASSWORD_RESET_DISABLED: ${{ secrets.KAMAL_PASSWORD_RESET_DISABLED }}
      SIGNUP_DISABLED: ${{ secrets.KAMAL_SIGNUP_DISABLED }}
      EMAIL_AUTH_DISABLED: ${{ secrets.KAMAL_EMAIL_AUTH_DISABLED }}
      INVITE_DISABLED: ${{ secrets.KAMAL_INVITE_DISABLED }}
      PRIVACY_URL: ${{ secrets.KAMAL_PRIVACY_URL }}
      TERMS_URL: ${{ secrets.KAMAL_TERMS_URL }}
      IMPRINT_URL: ${{ secrets.KAMAL_IMPRINT_URL }}
      GITHUB_ID: ${{ secrets.KAMAL_GITHUB_ID }}
      GITHUB_SECRET: ${{ secrets.KAMAL_GITHUB_SECRET }}
      GOOGLE_CLIENT_ID: ${{ secrets.KAMAL_GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.KAMAL_GOOGLE_CLIENT_SECRET }}
      AZUREAD_CLIENT_ID: ${{ secrets.KAMAL_AZUREAD_CLIENT_ID }}
      AZUREAD_CLIENT_SECRET: ${{ secrets.KAMAL_AZUREAD_CLIENT_SECRET }}
      AZUREAD_TENANT_ID: ${{ secrets.KAMAL_AZUREAD_TENANT_ID }}
      OIDC_CLIENT_ID: ${{ secrets.KAMAL_OIDC_CLIENT_ID }}
      OIDC_CLIENT_SECRET: ${{ secrets.KAMAL_OIDC_CLIENT_SECRET }}
      OIDC_ISSUER: ${{ secrets.KAMAL_OIDC_ISSUER }}
      OIDC_DISPLAY_NAME: ${{ secrets.KAMAL_OIDC_DISPLAY_NAME }}
      OIDC_SIGNING_ALGORITHM: ${{ secrets.KAMAL_OIDC_SIGNING_ALGORITHM }}
      CRON_SECRET: ${{ secrets.KAMAL_CRON_SECRET }}
      ASSET_PREFIX_URL: ${{ secrets.KAMAL_ASSET_PREFIX_URL }}
      NOTION_OAUTH_CLIENT_ID: ${{ secrets.KAMAL_NOTION_OAUTH_CLIENT_ID }}
      NOTION_OAUTH_CLIENT_SECRET: ${{ secrets.KAMAL_NOTION_OAUTH_CLIENT_SECRET }}
      STRIPE_SECRET_KEY: ${{ secrets.KAMAL_STRIPE_SECRET_KEY }}
      STRIPE_WEBHOOK_SECRET: ${{ secrets.KAMAL_STRIPE_WEBHOOK_SECRET }}
      GOOGLE_SHEETS_CLIENT_ID: ${{ secrets.KAMAL_GOOGLE_SHEETS_CLIENT_ID }}
      GOOGLE_SHEETS_CLIENT_SECRET: ${{ secrets.KAMAL_GOOGLE_SHEETS_CLIENT_SECRET }}
      GOOGLE_SHEETS_REDIRECT_URL: ${{ secrets.KAMAL_GOOGLE_SHEETS_REDIRECT_URL }}
      AIRTABLE_CLIENT_ID: ${{ secrets.KAMAL_AIRTABLE_CLIENT_ID }}
      ENTERPRISE_LICENSE_KEY: ${{ secrets.KAMAL_ENTERPRISE_LICENSE_KEY }}
      DEFAULT_TEAM_ID: ${{ secrets.KAMAL_DEFAULT_TEAM_ID }}
      DEFAULT_TEAM_ROLE: ${{ secrets.KAMAL_DEFAULT_TEAM_ROLE }}
      ONBOARDING_DISABLED: ${{ secrets.KAMAL_ONBOARDING_DISABLED }}
      CUSTOMER_IO_API_KEY: ${{ secrets.KAMAL_CUSTOMER_IO_API_KEY }}
      CUSTOMER_IO_SITE_ID: ${{ secrets.KAMAL_CUSTOMER_IO_SITE_ID }}
      RATE_LIMITING_DISABLED: ${{ secrets.KAMAL_RATE_LIMITING_DISABLED }}
      NEXT_PUBLIC_POSTHOG_API_KEY: ${{ secrets.KAMAL_NEXT_PUBLIC_POSTHOG_API_KEY }}
      NEXT_PUBLIC_POSTHOG_API_HOST: ${{ secrets.KAMAL_NEXT_PUBLIC_POSTHOG_API_HOST }}
      NEXT_PUBLIC_FORMBRICKS_API_HOST: ${{ secrets.KAMAL_NEXT_PUBLIC_FORMBRICKS_API_HOST }}
      NEXT_PUBLIC_FORMBRICKS_ENVIRONMENT_ID: ${{ secrets.KAMAL_NEXT_PUBLIC_FORMBRICKS_ENVIRONMENT_ID }}
      NEXT_PUBLIC_FORMBRICKS_ONBOARDING_SURVEY_ID: ${{ secrets.KAMAL_NEXT_PUBLIC_FORMBRICKS_ONBOARDING_SURVEY_ID }}
      NODE_ENV: production
      KAMAL_REGISTRY_USERNAME: ${{ secrets.KAMAL_REGISTRY_USERNAME }}
      KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
      KAMAL_CONTAINER_IMAGE: ${{ secrets.KAMAL_CONTAINER_IMAGE }}
      CLOUDFLARE_EMAIL: ${{ secrets.KAMAL_CLOUDFLARE_EMAIL }}
      CLOUDFLARE_DNS_API_TOKEN: ${{ secrets.KAMAL_CLOUDFLARE_DNS_API_TOKEN }}
      S3_ACCESS_KEY: ${{ secrets.KAMAL_S3_ACCESS_KEY }}
      S3_SECRET_KEY: ${{ secrets.KAMAL_S3_SECRET_KEY }}
      S3_REGION: ${{ secrets.KAMAL_S3_REGION }}
      S3_BUCKET_NAME: ${{ secrets.KAMAL_S3_BUCKET_NAME }}
      

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install kamal

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.KAMAL_SSH_PRIVATE_KEY }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Create builder
        run: docker buildx create --use --name formbricks-gh-actions-builder
        if: steps.buildx.outputs.should_create_builder == 'true'

      - name: Push env variables to Kamal
        run: |
          kamal() { command kamal "$@" -c kamal/deploy.yml; }
          kamal env push

      - name: Run deploy command
        run: |
          kamal() { command kamal "$@" -c kamal/deploy.yml; }
          set +e
          DEPLOY_OUTPUT=$(kamal setup 2>&1)
          DEPLOY_EXIT_CODE=$?
          echo "$DEPLOY_OUTPUT"
          if [[ "$DEPLOY_OUTPUT" == *"container not unhealthy (healthy)"* ]]; then
            echo "Deployment reported healthy container. Considering as success."
            kamal lock release
            exit 0
          else
            exit $DEPLOY_EXIT_CODE
          fi
        shell: bash
