name: Release on Dockerhub and GHCR

on:
  push:
    tags:
      - "v*"

jobs:
  release-image:
    name: Release on Multiple Registries
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/formbricks?schema=public"
      NEXTAUTH_SECRET: "8402fecffe4f0442e8d1c9882193588d7d717a0f106cc1592b0d0f0991261540"
      ENCRYPTION_KEY: "8402fecffe4f0442e8d1c9882193588d7d717a0f106cc1592b0d0f0991261540"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: laalshaitaan
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: shubhampalriwala
          password: ${{ secrets.GH_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get Release Tag
        id: extract_release_tag
        run: |
          TAG=${{ github.ref }}
          TAG=${TAG#refs/tags/v}
          echo "RELEASE_TAG=$TAG" >> $GITHUB_ENV

      - name: Build Docker image with multiple tags
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./apps/web/Dockerfile
          push: false
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/formbricks:${{ env.RELEASE_TAG }}
            ${{ secrets.DOCKER_USERNAME }}/formbricks:latest

            ghcr.io/shubhampalriwala/formbricks:${{ env.RELEASE_TAG }}
            ghcr.io/shubhampalriwala/formbricks:latest

          build-args: |
            NEXTAUTH_SECRET=${{ env.NEXTAUTH_SECRET }}
            DATABASE_URL=${{ env.DATABASE_URL }}
            ENCRYPTION_KEY=${{ env.ENCRYPTION_KEY }}

      - name: Push to Docker Hub
        run: |
          docker push laalshaitaan/formbricks:${{ env.RELEASE_TAG }}

      - name: Push to GHCR
        run: |
          docker push ghcr.io/shubhampalriwala/formbricks:${{ env.RELEASE_TAG }}
